# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import finai_service_pb2 as finai__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in finai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FinAiServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseTransaction = channel.unary_unary(
                '/finai.FinAiService/ParseTransaction',
                request_serializer=finai__service__pb2.TransactionRequest.SerializeToString,
                response_deserializer=finai__service__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.GenerateFinancialInsight = channel.unary_unary(
                '/finai.FinAiService/GenerateFinancialInsight',
                request_serializer=finai__service__pb2.InsightRequest.SerializeToString,
                response_deserializer=finai__service__pb2.InsightResponse.FromString,
                _registered_method=True)
        self.ChatWithAdvisor = channel.unary_unary(
                '/finai.FinAiService/ChatWithAdvisor',
                request_serializer=finai__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=finai__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ExtractReceiptData = channel.unary_unary(
                '/finai.FinAiService/ExtractReceiptData',
                request_serializer=finai__service__pb2.ReceiptRequest.SerializeToString,
                response_deserializer=finai__service__pb2.ReceiptResponse.FromString,
                _registered_method=True)
        self.DetectRecurringPayments = channel.unary_unary(
                '/finai.FinAiService/DetectRecurringPayments',
                request_serializer=finai__service__pb2.RecurringPaymentsRequest.SerializeToString,
                response_deserializer=finai__service__pb2.RecurringPaymentsResponse.FromString,
                _registered_method=True)
        self.DetectAnomalies = channel.unary_unary(
                '/finai.FinAiService/DetectAnomalies',
                request_serializer=finai__service__pb2.AnomalyRequest.SerializeToString,
                response_deserializer=finai__service__pb2.AnomalyResponse.FromString,
                _registered_method=True)
        self.CalculateGoalProjection = channel.unary_unary(
                '/finai.FinAiService/CalculateGoalProjection',
                request_serializer=finai__service__pb2.GoalProjectionRequest.SerializeToString,
                response_deserializer=finai__service__pb2.GoalProjectionResponse.FromString,
                _registered_method=True)


class FinAiServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ParseTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFinancialInsight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatWithAdvisor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractReceiptData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectRecurringPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateGoalProjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinAiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseTransaction,
                    request_deserializer=finai__service__pb2.TransactionRequest.FromString,
                    response_serializer=finai__service__pb2.TransactionResponse.SerializeToString,
            ),
            'GenerateFinancialInsight': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFinancialInsight,
                    request_deserializer=finai__service__pb2.InsightRequest.FromString,
                    response_serializer=finai__service__pb2.InsightResponse.SerializeToString,
            ),
            'ChatWithAdvisor': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatWithAdvisor,
                    request_deserializer=finai__service__pb2.ChatRequest.FromString,
                    response_serializer=finai__service__pb2.ChatResponse.SerializeToString,
            ),
            'ExtractReceiptData': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractReceiptData,
                    request_deserializer=finai__service__pb2.ReceiptRequest.FromString,
                    response_serializer=finai__service__pb2.ReceiptResponse.SerializeToString,
            ),
            'DetectRecurringPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectRecurringPayments,
                    request_deserializer=finai__service__pb2.RecurringPaymentsRequest.FromString,
                    response_serializer=finai__service__pb2.RecurringPaymentsResponse.SerializeToString,
            ),
            'DetectAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalies,
                    request_deserializer=finai__service__pb2.AnomalyRequest.FromString,
                    response_serializer=finai__service__pb2.AnomalyResponse.SerializeToString,
            ),
            'CalculateGoalProjection': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGoalProjection,
                    request_deserializer=finai__service__pb2.GoalProjectionRequest.FromString,
                    response_serializer=finai__service__pb2.GoalProjectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finai.FinAiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finai.FinAiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinAiService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/ParseTransaction',
            finai__service__pb2.TransactionRequest.SerializeToString,
            finai__service__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFinancialInsight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/GenerateFinancialInsight',
            finai__service__pb2.InsightRequest.SerializeToString,
            finai__service__pb2.InsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatWithAdvisor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/ChatWithAdvisor',
            finai__service__pb2.ChatRequest.SerializeToString,
            finai__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractReceiptData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/ExtractReceiptData',
            finai__service__pb2.ReceiptRequest.SerializeToString,
            finai__service__pb2.ReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectRecurringPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/DetectRecurringPayments',
            finai__service__pb2.RecurringPaymentsRequest.SerializeToString,
            finai__service__pb2.RecurringPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/DetectAnomalies',
            finai__service__pb2.AnomalyRequest.SerializeToString,
            finai__service__pb2.AnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateGoalProjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finai.FinAiService/CalculateGoalProjection',
            finai__service__pb2.GoalProjectionRequest.SerializeToString,
            finai__service__pb2.GoalProjectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
